checkForUpdatesAutomatically: false
showFlashSpace: opt+shift+space
showFloatingNotifications: false
showMenuBarTitle: false
showMenuBarIcon: true
menuBarTitleTemplate: $WORKSPACE_NUMBER
menuBarDisplayAliases: ''
enableFocusManagement: true
centerCursorOnFocusChange: false
focusLeft: opt+h
focusRight: opt+l
focusUp: opt+k
focusDown: opt+j
focusFrontmostWindow: false
enableSwipeGestures: true
swipeThreshold: 2e-1
restartAppOnWakeUp: false
swipeLeft3FingerAction: nextWorkspace
swipeRight3FingerAction: previousWorkspace
swipeUp3FingerAction: mostRecentWorkspace
swipeDown3FingerAction: showSpaceControl
swipeLeft4FingerAction: none
swipeRight4FingerAction: none
swipeUp4FingerAction: none
swipeDown4FingerAction: none
displayMode: dynamic
centerCursorOnWorkspaceChange: true
changeWorkspaceOnAppAssign: false
activeWorkspaceOnFocusChange: true
skipEmptyWorkspacesOnSwitch: false
keepUnassignedAppsOnSwitch: false
restoreHiddenAppsOnSwitch: false
enableWorkspaceTransitions: false
workspaceTransitionDuration: 1e-1
workspaceTransitionDimming: 5e-2
loopWorkspaces: true
loopWorkspacesOnAllDisplays: false
switchWorkspaceOnCursorScreen: false
switchToPreviousWorkspace: opt+left
switchToNextWorkspace: opt+right
switchToRecentWorkspace: opt+delete
assignFocusedApp: opt+p
unassignFocusedApp: opt+d
alternativeDisplays: ''
enablePictureInPictureSupport: true
switchWorkspaceWhenPipCloses: true
pipApps: []
pipScreenCornerOffset: 15
toggleTheFocusedAppFloating: opt+v
enableSpaceControl: true
showSpaceControl: opt+up
enableSpaceControlAnimations: true
enableSpaceControlTilesAnimations: true
spaceControlCurrentDisplayWorkspaces: false
spaceControlHideEmptyWorkspaces: false
spaceControlUpdateScreenshotsOnOpen: false
spaceControlNumberOfColumns: 4
enableIntegrations: false
runScriptOnLaunch: ''
runScriptOnWorkspaceChange: ''
runScriptAfterWorkspaceChange: ''
runScriptOnProfileChange: ''
